"""
Django settings for up_digital project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file-debug': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'simple',
            'filename': os.path.join(BASE_DIR, 'logs/debug.log'),
        },
        'file-info': { 
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'formatter': 'simple',
            'filename': os.path.join(BASE_DIR, 'logs/info.log'),
        },
        'file-error': { 
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'formatter': 'simple',
            'filename': os.path.join(BASE_DIR, 'logs/error.log'),
        }
    },
    'formatters': {
        'verbose': {
            'format': ('%(asctime)s [%(process)d] [%(levelname)s] ' + 'pathname=%(pathname)s lineno=%(lineno)s '
                       + 'funcname=%(funcName)s %(message)s '),
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '%(asctime)s %(levelname)s %(message)s',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console', 'file-info', 'file-debug', 'file-error'],
            'level': 'DEBUG',
            'propagate': True,
        }
    }
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u6%_2vidpu@q6$op-j#7le2rqkn2r*2v$o46l$7d^=sp8o0zh+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

SITE_ID = 4

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # Django REST framework 
    'rest_framework',
    # Bot application 
    'bot.apps.BotConfig',
    # CORS
    'corsheaders',
    # cron jobs
    'django_crontab',
    # social login
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    # celery
    'django_celery_beat',  # new addition
    'django_celery_results',  # new addition
    #paypal
    'paypal.standard.ipn',

]

AUTH_USER_MODEL = 'bot.User'

MIDDLEWARE = [
    # CORS
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'up_digital.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'up_digital.wsgi.application'

# celery configuration

CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'



# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# STATIC_URL = '/static/'
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]


STATICFILES_DIRS = (
	os.path.join(BASE_DIR,'static'),
)


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')



#paypal
PAYPAL_RECEIVER_EMAIL = 'sb-qf2fl25189505@business.example.com'
PAYPAL_TEST = True


# allauth / users
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_LOGIN_ON_GET=True

# LOGIN_REDIRECT_URL= '/sign-in/'
# LOGOUT_REDIRECT_URL= '/sign-in/'
LOGIN_REDIRECT_URL= '/'
LOGOUT_REDIRECT_URL= '/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
)

CORS_ORIGIN_ALLOW_ALL = True
# CORS_ORIGIN_WHITELIST = (
#     'http://localhost:8081',
# )


CRONJOBS = [
    # run every day at 12:08
    ('08 00 * * *', 'bot.utils.package_validity.run_user_validity'),
    # run every 30 min
    ('*/30 * * * *', 'bot.utils.keyword_search_schedule.run_keyword_search_schedule'),
    # run at the first day of each week
    ('1 0 * * *', 'bot.utils.keyword_search_schedule.create_keyword_search_schedule')
]

# Pokeman beast
# STRIPE_PUBLIC_KEY='pk_test_51M8SqmJCDPvINMYsH14jl6RLZmvLKdvRI0z9XirUlfAUpZicGWylWmeNJyrbH5uizuFg52alMg1M8yfkEUmzTXnx00LT05a7fU'
# STRIPE_PRIVATE_KEY='sk_test_51M8SqmJCDPvINMYsuaPJjqXR3Iqn3fGKwBKh9N1j7bJGtCOBw50ggU3Grn7TBz0bfKeH6cxqE9PPtn5wWFnix4se00XAo8i1pz'
STRIPE_PUBLIC_KEY='pk_live_51M8SqmJCDPvINMYsoD2aUt5sDXwh6JJz9PL45fP7h5N3KAFARAUPDdoXf8bwgJq0PetgQvOcNnTMtCL4uVosHFwd00pKJCyuVX'
STRIPE_PRIVATE_KEY='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'

SOCIALACCOUNT_PROVIDERS={
        'google': {
            'APP': {
                'client_id': '859054605714-6gv3ocr14vq8ku4kb74k96o605hmvbho.apps.googleusercontent.com',
                'key': 'google',
                'secret': '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'
            }
        },
        'facebook': {
            'APP': {
                'client_id': '323034298456-05j530e69mu84q9h9d32iv4nnhg3dtjt.apps.googleusercontent.com',
                'key': 'facebook',
                'secret': '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'
            }
        }
    }



# GP_CLIENT_ID="859054605714-76tj1s32ppjvnhj2j7m0lu1e8cl7rcv7.apps.googleusercontent.com"
# GP_CLIENT_SECRET="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"
GP_CLIENT_ID="859054605714-6gv3ocr14vq8ku4kb74k96o605hmvbho.apps.googleusercontent.com"
GP_CLIENT_SECRET="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"
# Farrukh
# GP_CLIENT_ID="323034298456-34iu0ebmn1c5b7v3ph7s367cqbdp8j63.apps.googleusercontent.com"
# GP_CLIENT_SECRET="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"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'hello@ctrboss.com'
EMAIL_HOST_PASSWORD = 'dzjdiijznfhseqhm'