# Generated by Django 3.2.15 on 2022-11-07 17:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('value', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='SearchPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(verbose_name='Cost')),
                ('total_pages', models.IntegerField(verbose_name='Number of Pages')),
                ('onsite_time', models.IntegerField(verbose_name='Time on Site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Campaign Description'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='Schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 17, 3, 40, 765096), verbose_name='Search Result schedule'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='pages',
            field=models.TextField(blank=True, null=True, verbose_name='Search Pages'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Search Result Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='searches_status',
            field=models.BooleanField(default=False, verbose_name='Searches Status'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='country',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='searches_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pages Per Session'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Website Rank in Search'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='Search Results'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='website_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Website Title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='searches',
            field=models.IntegerField(default=0, verbose_name='Allowed Searches'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default='False')),
                ('amount', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'Paypal'), ('crypto_currency', 'Crypto Currency')], default='stripe', max_length=100, verbose_name='Paying Source')),
                ('subscriptionID', models.CharField(default=None, max_length=800)),
                ('subscriptionNumber', models.CharField(blank=True, max_length=800, null=True)),
                ('clientID', models.CharField(blank=True, max_length=800, null=True)),
                ('description', models.CharField(default=None, max_length=800, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('value', models.CharField(max_length=800)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stateCountryID', to='bot.country')),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('value', models.CharField(max_length=800)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityCountryID', to='bot.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stateID', to='bot.state')),
            ],
        ),
    ]
