# Generated by Django 3.2.15 on 2022-11-17 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20221107_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='active_device',
            field=models.CharField(blank=True, choices=[(0, 'Laptop'), (1, 'Tablet'), (2, 'Mobile Phones')], max_length=100, null=True, verbose_name='Active Device'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='time_on_site',
            field=models.IntegerField(default=0, verbose_name='Time on Site'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='Schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 19, 18, 14, 900985), verbose_name='Search Result schedule'),
        ),
    ]
