# Generated by Django 3.2.15 on 2022-11-27 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20221120_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='direction',
            field=models.BooleanField(default=False, verbose_name='Website Directions'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='knowledge_panel',
            field=models.BooleanField(default=False, verbose_name='Knowledge Panel'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='Schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 9, 11, 35, 192682), verbose_name='Search Result schedule'),
        ),
    ]
