# Generated by Django 3.2.15 on 2022-12-04 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20221203_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='direction_URL',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Direction URL'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='Schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 20, 7, 11, 476429), verbose_name='Search Result schedule'),
        ),
    ]
