# Generated by Django 3.2.15 on 2022-12-11 18:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20221204_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchplan',
            name='daily_searches',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of searches per day'),
        ),
        migrations.AddField(
            model_name='searchplan',
            name='planID',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plan ID'),
        ),
        migrations.AddField(
            model_name='searchplan',
            name='searche_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Cost per search'),
        ),
        migrations.AddField(
            model_name='searchplan',
            name='stripe_price_ID',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Stripe Price ID'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='map_campaign_direction',
            field=models.BooleanField(default=False, verbose_name='Map Campaigns with Directions'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='avg_session_duration',
            field=models.IntegerField(default=70, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(70)], verbose_name='Average Session Duration'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='pages_per_session',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Pages Per Session'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='Schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 18, 33, 10, 11373), verbose_name='Search Result schedule'),
        ),
    ]
