# Generated by Django 3.2.15 on 2023-01-07 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20230104_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='strip_client_ID',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Stripe Client ID'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='Schedule',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Search Result schedule'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=800, null=True),
        ),
        migrations.CreateModel(
            name='monthlyBillReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_ID', models.CharField(blank=True, max_length=800, null=True)),
                ('body_created', models.DateTimeField(blank=True, null=True)),
                ('account_name', models.CharField(blank=True, max_length=800, null=True)),
                ('object_charge', models.CharField(blank=True, max_length=800, null=True)),
                ('charge', models.CharField(blank=True, max_length=800, null=True)),
                ('obj_created', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=800, null=True)),
                ('customer', models.CharField(blank=True, max_length=800, null=True)),
                ('hosted_invoice_url', models.CharField(blank=True, max_length=800, null=True)),
                ('invoice_pdf', models.CharField(blank=True, max_length=800, null=True)),
                ('total', models.FloatField(blank=True, default=0, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=800, null=True)),
                ('payment_intent', models.CharField(blank=True, max_length=800, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=800, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=800, null=True)),
                ('request_idempotency_key', models.CharField(blank=True, max_length=800, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_monthly_sheet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
